name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  build:
    strategy:
      matrix:
        node: [ 18, 20 ]

    name: Build Package (Node ${{ matrix.node }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Build package
        run: yarn build

      - name: Lint
        run: yarn lint && yarn lint:package

      - name: Run tests against browser
        run: yarn test
