name: Publish Release

on:
  workflow_dispatch:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Build package
        run: yarn build

      - name: Publish release to NPM
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
